{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vince.fullname" . }}
  labels:
    app: plausible
  {{- include "vince.labels" . | nindent 4 }}
type: Opaque
data:
  VINCE_ADMIN_NAME: {{ .Values.secret.adminName | toString | b64enc }}
  VINCE_ADMIN_EMAIL: {{ .Values.secret.adminEmail | toString | b64enc }}
  VINCE_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | toString | b64enc }}
  {{- if .Values.acme.enabled }}
  VINCE_ACME_EMAIL: {{ .Values.acme.email | toString | b64enc }}
  VINCE_ACME_DOMAIN: {{ .Values.acme.domain | toString | b64enc }}
  {{- end }}
{{- end }}